### ISSUE TITLE
Contest Clarification Global Notification

### ISSUE THREAD

**Issue by ZsgsDesign** [ZsgsDesign/NOJ#100]
Contest Clarification Global Notification

**Comment by ZsgsDesign** [comment]
Using `notice` in the primaryJS to send global notification. Try not send multiple notifications when you got multiple tabs on one ceratin contest. Adding an custom icon and do remember to modify `.gitignore` if necessary.

**Comment by X3ZvaWQ** [comment]
It's done, maybe.
Comment if unexpected behavior occurs or  need to add more requirements
