### ISSUE TITLE
Some problems to install

### ISSUE THREAD

**Issue by xzm2000** [ZsgsDesign/NOJ#102]
I try to install this oj in my server, but I have some unexpected errors.

When I went to step 8, after I add `* * * * * php /path-to-noj/artisan schedule:run` in the file edited, I run `php artisan queue:work --queue=noj,codeforces,contesthunter,poj,vijos,pta,uva`. It shows error.

```
   Predis\Connection\ConnectionException  : Connection refused [tcp://127.0.0.1:6379]

  at /var/www/html/oj/vendor/predis/predis/src/Connection/AbstractConnection.php:155
    151|      */
    152|     protected function onConnectionError($message, $code = null)
    153|     {
    154|         CommunicationException::handle(
  > 155|             new ConnectionException($this, static::createExceptionMessage($message), $code)
    156|         );
    157|     }
    158| 
    159|     /**


  Exception trace:

  1   Predis\Connection\AbstractConnection::onConnectionError("Connection refused")
      /var/www/html/oj/vendor/predis/predis/src/Connection/StreamConnection.php:128

  2   Predis\Connection\StreamConnection::createStreamSocket(Object(Predis\Connection\Parameters), "tcp://127.0.0.1:6379")
      /var/www/html/oj/vendor/predis/predis/src/Connection/StreamConnection.php:178

  Please use the argument -v to see more details.

```

I wanna know what problem may I have. Thanks!

I think maybe I have problems when I edit `.env`. I just changed the database user and password. Should I change others?

**Comment by ZsgsDesign** [comment]
Hi, it looks like you haven't install Redis, NOJ now requires Redis support. See `.env.example` , our cache system uses them.

**Comment by ZsgsDesign** [comment]
Updated Dependencies List

**Comment by xzm2000** [comment]
I try again this morning but failed again.

This time when I I run `php artisan queue:work --queue=noj,codeforces,contesthunter,poj,vijos,pta,uva`, it shows nothing and it got stuck. Do you know what may problems are? Or where can I use the logs. Thank you!

**Comment by ZsgsDesign** [comment]
artisan queue is a daemon, it listens the submission and push it to the remote judge, supervisor is recommended for lasting monitoring.

**Comment by ZsgsDesign** [comment]
Please reopen the issue beforehand or we would not be able to receive notifications.
