### ISSUE TITLE
Some recommended new functions

### ISSUE THREAD

**Issue by SinonJZH** [ZsgsDesign/NOJ#15]
## Rating System
- [x] A system to calculate users rating (like codeforces)after every contest
## Gaming Competition system
- [x] Add a new competition system.A system like codeforces, in which participants can hack other's code to get points.
## Tutorial Mode
- [ ] Add a tutorial mode for beginners to learn algorithm. It could be problem sets, or some blogs about algorithm.

**Comment by ZsgsDesign** [comment]
The rating system's already on schedule which would be supported in later this year. About gaming system, we are still on to it. Tutorial Mode is excellent, much like Luogu's training area and we are seeking the support of that from third party too.

**Comment by SinonJZH** [comment]
I came up a new recommend recently.I think it's better to change CodeForces‘ default language from C to C++ 😆

**Comment by ZsgsDesign** [comment]
Please try issuing all requests seperately ,for that would be easier for us to add tags/close and so on.

**Comment by ZsgsDesign** [comment]
Gaming Competition system was off schedule and Tutorial Mode would be released in 0.3.0
