### ISSUE TITLE
Unexpected offset of textareas

### ISSUE THREAD

**Issue by xgsteins** [ZsgsDesign/NOJ#200]
**Describe the bug**  
In Solution page, there exists some unexpected offset of textareas.

**To Reproduce**  
Go to https://acm.njupt.edu.cn/problem/CF1163B2/solution, and then the textarea of the solution made by B18030519 covers other blocks.

**Screenshots**  
![(7Z}4P(5BGBT1ZBFE0(S3RX](https://user-images.githubusercontent.com/33283328/61894606-642f4580-af43-11e9-93b2-a43ca79a060d.png)

**System (please complete the following information):**
 - OS:  Windows 10 Home 1809
 - Browser: chrome
 - Version: 75.0.3770.142
 - Device: Surface Go
 - Image resolution: 1800*1200

**Comment by ZsgsDesign** [comment]
We have reproduced this issue and have located the source. It's actually wired for we have fixed that once.

**Comment by ZsgsDesign** [comment]
It's a side effect since Chrome modified flex mechanism at 72. Issues about Immersive Editor have been fixed but other codes haven't. Thank you.
