### ISSUE TITLE
Ranking information display for synchronized contests

### ISSUE THREAD

**Issue by zhaoyw1999** [ZsgsDesign/NOJ#225]
The original ranking list can be displayed after the synchronized contest.

**Comment by ZsgsDesign** [comment]
Scheduled for hotfix, shall be released a few days later.

**Comment by Brethland** [comment]
Well, infact this is ConePi's work to store rank from cache to database for future usage.

**Comment by ZsgsDesign** [comment]
@pikanglong Hotfix or not?

**Comment by pikanglong** [comment]
Maybe I will fix this a year later.
