### ISSUE TITLE
About Submit Code

### ISSUE THREAD

**Issue by Wonz5130** [ZsgsDesign/NOJ#28]
**Describe the bug**
I find that I can't submit code when I use Chrome during the recent `HuaWei Contest` . I `Ctrl+C` my code, but can't `Ctrl+V` in the submit page.

**Screenshots**
![image](https://user-images.githubusercontent.com/35889526/54358501-85ca1780-469b-11e9-922a-e8477bca6dcb.png)

**System (please complete the following information):**
 - OS: [Windows]
 - Browser: [Chrome]
 - Version: [72.0.3626.121]

**Comment by ZsgsDesign** [comment]
Sorry about that but we can't reproduce the situation, the general solution is to check Chrome update, NOJ may require Chrome 62 and later to work properly but you are using Chrome 72 already. 

The error display is a bug, it actually means your submission didn't pass the validator, which in this case, did not submit your code. Please let me know if you solved the problem.

**Comment by Wonz5130** [comment]
> Sorry about that but we can't reproduce the situation, the general solution is to check Chrome update, NOJ may require Chrome 62 and later to work properly but you are using Chrome 72 already.
> 
> The error display is a bug, it actually means your submission didn't pass the validator, which in this case, did not submit your code. Please let me know if you solved the problem.

Then I use IE to solve this problem. Thanks.
