### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by dgsyrc** [ZsgsDesign/NOJ#280]
在云端打开/public/install.php时显示红字'Sorry, ./vendor/autoload.php is not existed. Are you sure all dependencies have installed yet?'

是github项目这边遗漏了上传autoload.php吗

**Comment by ZsgsDesign** [comment]
run `composer install` as the guide said. See Installation Step 4. The `install.php` only process environment files and we recommend following the installation guide instead of using web installer.

[Installation Guide](https://github.com/ZsgsDesign/NOJ#installation)

**Comment by ZsgsDesign** [comment]
You are more than welcomed to join our QQ Group **668108264** for further tech support.
