### ISSUE TITLE
Add copy function of input examples

### ISSUE THREAD

**Issue by Wonz5130** [ZsgsDesign/NOJ#29]
**My feature request about `Copy` button**
Like luogu, can copy the input examples by click the `Copy` button instead of `Ctrl+C` after selecting these examples.

**Take luogu as an example**
![image](https://user-images.githubusercontent.com/35889526/54359124-f0c81e00-469c-11e9-803d-ad747220cb41.png)

**Comment by ZsgsDesign** [comment]
This is a scheduled new feature and we are going to support that till the end of this week.

**Comment by Wonz5130** [comment]
> This is a scheduled new feature and we are going to support that till the end of this week.

Thanks. I hope that NOJ will become better Online Judge sincerely.

**Comment by ZsgsDesign** [comment]
Already done.
