### ISSUE TITLE
关于对Aizu远端测评支持的请求

### ISSUE THREAD

**Issue by skippre** [ZsgsDesign/NOJ#302]
能不能添加对Aizu远端的资瓷，我最近学<<挑战>>那套书没得梯子做题就碰壁了。 另外，vjudge的Aizu也早就挂了。
有个拙见，其实像BZOJ、HDUOJ、ZOJ、POJ、etc这些国内访问没问题的OJ也许不必要资瓷远端，反而国外的如SPOJ等需求更多一点吧。

**Comment by ZsgsDesign** [comment]
Thank you for opening an issue for NOJ. I would answer your questions above:

>能不能添加对Aizu远端的资瓷，我最近学<<挑战>>那套书没得梯子做题就碰壁了。 

Actually we never considered NOJ as a virtual private network for users so they can handle solutions to OJs that are blocked or jammed so it's a big surprise to me. But I must say some users may already use NOJ that way. We are currently developing the interface for **SPOJ**. I would add **Aizu** to the issues list but it may come out very late. Maybe next month it can be up and running.

> 另外，vjudge的Aizu也早就挂了。

Well, **vjudge** may out of maintenance for a while :-)

> 有个拙见，其实像BZOJ、HDUOJ、ZOJ、POJ、etc这些国内访问没问题的OJ也许不必要资瓷远端，反而国外的如SPOJ等需求更多一点吧。

Thank you again for your insight. The very reason we support other online judges is that we can provide a platform that contains all the problems you need. Then you can create contests across several online judges or do other things inside our platform. Sure OJs like HDU or POJ could be accessed directly. But with the help of NOJ, we now can have a group contest containing problems of both OJ and even track team members training data and rate them inside a group. As a matter of fact, we are building the ultimate unified environment for OI/ICPC training.
