### ISSUE TITLE
noj支持docker安装吗？

### ISSUE THREAD

**Issue by CrazyBoyM** [ZsgsDesign/NOJ#304]
你好，我想知道noj是否提供了docker的安装方式

**Comment by ZsgsDesign** [comment]
NOJ currently does not provide a docker image, as docker may raise performance issues. However, we may support docker in the near future as a second choice, but it would definitely come after the release of `0.4.1`.

If you require assistance about installing NOJ, you can check our README or Wiki or using this, note that it's now a beta version: [NOJ Documentation](https://njuptaaa.github.io/docs/). You can also join our QQ Group **668108264** .

Below is some projects related to NOJ that supports/will support docker:

**NOJ Slim** is a special edition of NOJ which focused on single-contest holding and provides with a handful of tools for managing offline contests would come up with docker support, for this version is provided to those who may not know Linux Server maintenance well.

**NOJ_JudgeServer** is NOJ's JudgeServer and it can be installed via docker.

**Comment by ZsgsDesign** [comment]
@CrazyBoyM I will close this issue for there are no further questions.
