### ISSUE TITLE
提交错误

### ISSUE THREAD

**Issue by CrazyBoyM** [ZsgsDesign/NOJ#319]
你好，我前台一直提交错误，后台log如下：
1 excepuo . WLp[stacktrace]

oOintena lncto llminanunt handeror aray, randO: uwwwwl.Arao ..i wwwworetopasubutterpp aray. randAray

2 lwww gda.corkgrbesubmi/submitrt p5); ApplBaleruatinlptalbuit costut(rayaAraywwwoo gcay c/lgkekae/pplstecratepta,Ara24 /wwwwwwawcwgeew.lappbebe4 plBabelSumitSubut constructArayas  php[39): ApplabelelBabel >submitAray=6 Intenal function]: pplUoslProcessusmissioa

7 lwwwowge.ovdo/arovertererrciaotiouetd.hp(32) call, user. func aaylAray,Arrayw/wwwott.gdta agekekveveodoaraelerclinateContanlluminatelContalnerlBouetodlminateontan

. /wwwww.gcaycwgkovendoraraverteluinatelContaine3

luiniateContanindeminatoudanlapa Aray, Obec(losure)) .#l0 wwowittgd angekekevendofoaraverrerinateContanontalimitatlntanenelBoudndeliouniplicationrayArray NULL

en lwww tgdyovecooaecminasDis php[94; llinatelContainlContai allrayn12 lwww gdayacgeelenoaener php(128): llimimlaBusltpat lilinatelBusObjectlApplJobslProcesmis

13 wwwwwwaph(l0 llminaeilelpipeli Hllinatall(ObjectApplJobslProcesSubmis

и Hww gdoyuogaosp phpep lumimlalilnelPie thenObjctCl15 uwocuaphp(e9:9 lunaleulDepat

**Comment by ZsgsDesign** [comment]
Thank you for opening an issue for NOJ.

Your log seems strange and nearly unreadable, you can read logs from the admin panel instead.
If you are viewing the raw files, try the `storage/logs` folder.

For the currently posted log, I can only assume there is an Exception while processing submission and randArray function throws it.

So if I am correct, try adding judgers firsthand. We would add a human-readable notice in the next version.
