### ISSUE TITLE
能否加入对中文的支持

### ISSUE THREAD

**Issue by oier-byh** [ZsgsDesign/NOJ#410]
如题

**Comment by ZsgsDesign** [comment]
目前已经完成：首页、题库、训练场、状态、排行榜。
进行中：比赛、小组、用户中心、后台。

**Comment by ZsgsDesign** [comment]
We would fully support `en` and `zh-CN` in 0.5.0, other ISO sanctioned languages except for `tlh` would have limited support over common terms, admin, auth, and validator.
