### ISSUE TITLE
Bug about board frozen announcenment

### ISSUE THREAD

**Issue by Brethland** [ZsgsDesign/NOJ#43]
**Describe the bug**
A display exception that after contests the description of board's frozen status is still viewable. 

**To Reproduce**
1. Go to Contest.
2. Click on any contest that has board frozen system and has ended.
3. Go to rank page.
4. See error.

**Expected behavior**
The alert should been hidden.

**System**
 - OS:Windows 10 Professional 1809
 - Browser:Chrome 72

**Comment by ZsgsDesign** [comment]
It's intended to do so but telling the viewers that the board doesn't represent the final standings. If a contest requires board frozen, usually it would roll out the board later, and release frozen status immediately after the contest is not what they want.
