### ISSUE TITLE
Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

### ISSUE THREAD

**Issue by BarryBooder** [ZsgsDesign/NOJ#483]
完整错误信息如下：
Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

Warning: array_map() expects parameter 1 to be a valid callback, no array or string given in /data/oj/vendor/vlucas/phpdotenv/src/Lines.php on line 114

**Comment by BarryBooder** [comment]
已经解决， storage 目录权限 775 不够，得给 777

**Comment by ZsgsDesign** [comment]
By making the folder the same user/usergroup you can avoid `777` security concerns, e.g., `www` is your nginx/apache user you can `chown -R www:www ./` thus making the whole folder `www`'s.
