### ISSUE TITLE
404 Everywhere

### ISSUE THREAD

**Issue by sunist-c** [ZsgsDesign/NOJ#501]
I deploy NOJ as the docs said, just change `.env` file for database.

But finished all steps, I can noly visit the index page, when I click the label and visit other pages, it returns 404

I use bt panel to install some environment such as `PHP`, `Mysql`, `Redis`, is it wrong?

Platform:
Ubuntu 18.04 (tencent CVS)
Mysql 5.7
PHP 7.3
Redis 6.0

**Comment by ZsgsDesign** [comment]
Looks like you are having a rewrite problem.

**Comment by ZsgsDesign** [comment]
Try using `.htaccess` for Apache or `.conf` for Nginx, here is one rewrite example:
```nginx
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```
Here is one Apache `.htaccess` (NOJ has that included) example:
```apache
Options +FollowSymLinks -Indexes
RewriteEngine On

RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```
The ultimate goal is to redirect the majority of the requests to `index.php`.

**Comment by ZsgsDesign** [comment]
If your problem persists, comment below.

**Comment by sunist-c** [comment]
Problem resolved, thanks!
