### ISSUE TITLE
然后我发现了不少bug

### ISSUE THREAD

**Issue by ChthollyNephren** [ZsgsDesign/NOJ#512]
从[YZOJ](http://oj.yzzx.org/)那里看过来的，恕我提出一些目前发现的Bug

1. 邮件验证用不起来，会出问题

2. 有些界面点进去之后没有返回按钮（包括顶部的标题栏也不见了），只能用浏览器的返回按钮

3. 创建群组时有"公开"选项，然而实际上没有公开（luogu团队以前都是可以公开的，我觉得那样挺好）

4. 团队没有什么可用操作，题目管理中创建不了题目，子群组功能用不了

5. 不能查看单个题目的所有提交记录

6. 个人信息能看到的太少了，比如提交记录就没有

7. 排行榜中只有管理员（还有：为什么账号一注册等级就是"专家"），团队邀请的时候要写邮箱也听麻烦。建议和洛谷类似，每个用户搞一个id，可以通过id来查看个人信息等等

8. 比赛搞得感觉太单一了，没有什么tag，也没有比赛类型

9. 发布公告就只有一个“群组宣言”什么的，。。。团队内也没有什么讨论的

10. 不过感觉相比以前的YZOJ要好多了！感谢张总！

我的YZOJ账号名：damage

（抱歉提的问题有点多，还有一些无理的要求）

**Comment by ZsgsDesign** [comment]
1. 邮箱还没配呢，上午看到有这个问题，可能是没开SMTP；
2. 没有返回按钮的页面（没懂？）；
3. 创建群组的公开是公开，首页推荐的12个群组为了高并发设置了缓存，实际上公开和私有的主要区别是公开可通过链接访问，私有不可以；
4. 团队操作包括了群组公告、新建比赛、发起训练赛、组内成员数据分析等等，子小组没做，题目管理因为目前没有下放到前台，只能通过Admin Portal新增；
5. 可以呀，在“状态”可以进行筛选，只会显示非比赛的提交；
6. 个人信息只提供了通过题目列表，可以通过“状态”筛选查看，后面可以加到个人页面；
7. 排行榜每天凌晨刷新一次（也是为了高并发），可以通过Admin Portal刷新，新加入用户有两个等级，一个是Casual Rank，开始是Recruit，一个是Professional Rank，开始是Specialist，两个是独立的评级系统，Casual是满足正态分布定义的，Professional也是类似CodeForces的排位算法，这种算法要求初始分数位于中位；
8. 比赛Tag以前准备加的，类型不太懂，现在支持IOI和ICPC，两种模式下还有custom选项，但是也没有放在前台，而是Admin Portal设置；
9. 讨论版可以加，应该排这个feature了；
