### ISSUE TITLE
新增题目时，没有可供选择的OJ

### ISSUE THREAD

**Issue by fearlessxjdx** [ZsgsDesign/NOJ#544]
我按照 https://njuptaaa.github.io/docs/#/noj/guide/docker 中的 `docker-compose.yml` 。

修改了 noj 的向外端口号，并将其他 port 都注释掉了，不向外。up后，注册功能正常，想新增题目时，发现无可供选择的 OJ，无法添加题目，示图如下。

请问出现这个问题的原因可能是什么？

![image](https://user-images.githubusercontent.com/17431574/109956121-3f55a380-7d1e-11eb-92b2-26cff5ad235c.png)

**Comment by fearlessxjdx** [comment]
> ```
> php artisan babel:install noj
> ```
@ZsgsDesign 执行过，但是报了个错误当时没在意。
![image](https://user-images.githubusercontent.com/17431574/110054837-cd6d7080-7d96-11eb-9346-1b49da7ffc71.png)

**Comment by ZsgsDesign** [comment]
The upgrade button is abandoned right now because we are planning to use docker distribution instead.

the version indicator relys on the git tag and commit info, so only the `git clone` deploy method has it shown.

**Comment by fearlessxjdx** [comment]
> The upgrade button is abandoned right now because we are planning to use docker distribution instead.
> 
> the version indicator relys on the git tag and commit info, so only the `git clone` deploy method has it shown.

@ZsgsDesign Why is there an error when I running `php artisan babel:install noj` , how can I fix it?

**Comment by ZsgsDesign** [comment]
what kind of error? You need to post any error response that shown on console or admin logger or I can't help you solve that.

**Comment by fearlessxjdx** [comment]
@ZsgsDesign 感谢您的回复

我是使用 https://njuptaaa.github.io/docs/#/noj/guide/docker 中的 `docker-compose.yml` up 的。

我看了下，这个容器大约按顺序执行了以下步骤：

1. php artisan key:generate --ansi
2. composer install
3. composer update
4. php artisan migrate --force
5. php artisan serve --host=0.0.0.0 --port=3000

随后，网页的注册、登入都正常。但是，我进入 admin 页面添加题目时，发现没有可供选择的 OJ。

我便尝试执行了以下步骤，但均有报错

**php artisan babel:install noj -vvv**

<img src="https://user-images.githubusercontent.com/17431574/110054837-cd6d7080-7d96-11eb-9346-1b49da7ffc71.png" width = "70%" alt="" />

**php artisan babel:update noj -vvv**

```
Updating noj

   Exception  : No available download link.
```

我没能找到更详细的日志，我只操作过 `noj` 容器，`judge_server` `db` 等容器，我并未做任何操作。`git status` 显示，除了 `composer.lock` 文件外，其他文件也均未有更改。

我该如何处理这个问题？安装步骤上是否有所缺失？

**Comment by ZsgsDesign** [comment]
I will look into that, thank you.

**Comment by LengYuna** [comment]
> I will look into that, thank you.

maybe some DB::function() were not correct

**Comment by LengYuna** [comment]
@fearlessxjdx 
您好，最近我也在尝试部署NOJ，但是总是以失败告终，不知能否参考一下您的 `docker-compose.yml` 文件，万分感谢！！

**Comment by fearlessxjdx** [comment]
> @fearlessxjdx
> 您好，最近我也在尝试部署NOJ，但是总是以失败告终，不知能否参考一下您的 `docker-compose.yml` 文件，万分感谢！！

我也没成功，我仅仅是 web 端成功了，无法添加题目和评测，我也在等大佬解答。。。

**Comment by ZsgsDesign** [comment]
@fearlessxjdx @LengYuna It's a PHP 7.4 compatibility issue and has been fixed so far in `dev` branch. A stable version shall release next week with tons of new features already available in `dev`.
