### ISSUE TITLE
Compile Info: No Available Judger.

### ISSUE THREAD

**Issue by LengYuna** [ZsgsDesign/NOJ#574]
![QQ截图20210422205143](https://user-images.githubusercontent.com/48179733/115717341-abfb2f00-a3ac-11eb-9d0d-82dff0e5cecc.png)

When I submit the code, I got this info.
How to deploy the Judger?
Any help?

**Comment by YZ-HL** [comment]
你需要在服务器上配置JudgeServer（或许还需要配置测试数据同步）。

近几天我在配置NOJ，并编写了一个简易指南，可以参考一下：[NOJ部署指北](https://liushan.site/2021/08/04/NOJ%EF%BC%88%E5%8D%97%E9%82%AEOJ%EF%BC%89%E6%9E%84%E5%BB%BA%E6%8C%87%E5%8C%97/#Docker-%E8%AF%84%E6%B5%8B%E6%9C%BA-amp-%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%E5%90%8C%E6%AD%A5)
