### ISSUE TITLE
Disable Registration 禁止注册

### ISSUE THREAD

**Issue by phantomlsh** [ZsgsDesign/NOJ#586]
**Is your feature request related to a problem? Please describe.**
In some cases like in the Highschool, the system is required to be placed under restriction. For example, only authorized users can access the system, with pre-defined accounts or SSO.

**Describe the solution you'd like**
First of all, a config setting could be added to disable registration. (is there one?)
Then, a customized SSO interface may be added to enhance the user control, linking the user identity across several systems.

**Describe alternatives you've considered**
For the second part, OAuth may also work, but with more complexity.

**Additional context**
Features like SSO can be configured (enable/disable)

**Comment by ZsgsDesign** [comment]
Done
