### ISSUE TITLE
Add "history submission" to each problem in problem bank

### ISSUE THREAD

**Issue by Heartfirey** [ZsgsDesign/NOJ#727]
**Add "history submission" to each problem in problem bank**
When we finish a problem and submit it to NOJ, we can only get a state back(Accepted etc.). And the next time we opened the problem, we can only get the code we submitted the last time though we may submitted serval times.
So I recommended this function to NOJ, everyone could see their own submissions through a separate page. 
Take it for example: Luogu-Record:
![image](https://user-images.githubusercontent.com/51751659/136561552-f075f9cd-728b-458e-b015-892d3a09d0d5.png)
Site: https://www.luogu.com.cn/record
If it's possible, I recommended NOJ added this function as a new features in version 0.18 or 0.17.1 Characinae Build Pack 1.

**Comment by ZsgsDesign** [comment]
There are two ways available here. In problem editor, you can click the history button on the lower right side and then click one of the records to view full details. Or you can navigate to the status page and use a filter to see your submission history.
