### ISSUE TITLE
compile info

### ISSUE THREAD

**Issue by mlb0925** [ZsgsDesign/NOJ#809]
/judger/spj/spj-001#1637686624.c:1:1: error: stray '\346' in program
    1 | 无
      | ^
/judger/spj/spj-001#1637686624.c:1:2: error: stray '\227' in program
    1 | 无
      |  ^
/judger/spj/spj-001#1637686624.c:1:3: error: stray '\240' in program
    1 | 无
      |   ^
有什么解决办法没有

**Comment by ZsgsDesign** [comment]
You have unprocessable characters in your SPJ source code. You can paste the source code as a file here. Right now it looks like whitespace but in full-width.

**Comment by ZsgsDesign** [comment]
`\240` is non-breaking space in ISO8859-1 encoding, looks like you need to check your whitespace more carefully.
