### ISSUE TITLE
代码在线运行 runtime ERR，但在IDE 运行没问题，没有任何特殊代码，麻烦看下什么原因

### ISSUE THREAD

**Issue by chanbaihai** [ZsgsDesign/NOJ#917]
**Describe the bug**
代码在线运行 runtime ERR，但在IDE 运行没问题，没有任何特殊代码，麻烦看下什么原因
![微信图片_20220310185248](https://user-images.githubusercontent.com/36693835/157647738-aabe6354-b76c-49ad-aa27-f7104ebf2def.png)

![image](https://user-images.githubusercontent.com/36693835/157648199-cc46b148-cf38-447c-9c6e-4605aca2f84c.png)

![微信图片_20220310185233](https://user-images.githubusercontent.com/36693835/157647821-92790601-d5ed-4591-b70b-6673feabd89b.png)

**Comment by ZsgsDesign** [comment]
@chanbaihai 看起来似乎是输入处理有问题？

**Comment by chanbaihai** [comment]
希望能增加报错提示信息，把编译错误或者是答案错误抛出，让用户看到，目前遇到编译器和在线运行结果不一致的问题不好排查

**Comment by ZsgsDesign** [comment]
@chanbaihai 对于python这类解释型语言，这类运行时错误没有办法解析为编译错误，对于python的静态错误NOJ会返回编译错误，对于编译型语言也是如此；这种情况并非答案错误，而是解释器遇到了Fatal Error，因此抛出运行时错误，指代程序未正常结束，这是这段代码预期得到的评测结果。

**Comment by chanbaihai** [comment]
> @chanbaihai 对于python这类解释型语言，这类运行时错误没有办法解析为编译错误，对于python的静态错误NOJ会返回编译错误，对于编译型语言也是如此；这种情况并非答案错误，而是解释器遇到了Fatal Error，因此抛出运行时错误，指代程序未正常结束，这是这段代码预期得到的评测结果。在程序正常结束但是答案不正确的时候，将会返回答案错误。

[非常疑惑NOJ是如何判断答案正确与否的，我在做这题的时候用python3](https://acm.njupt.edu.cn/problem/NOJ1004/editor) 提交显示 wrong answer，我从solution里面找了一个正确的C答案本地运行，相同的输入与我的输出一样，但用python提交一致就是 wrong answer，找了一天实在没找到原因，希望您方便的时候能看下什么原因，下面附上代码与截图
![image](https://user-images.githubusercontent.com/36693835/158113463-4df34434-64ab-439c-bc0b-a45b35822a76.png)

![image](https://user-images.githubusercontent.com/36693835/158113636-ea3601e4-71a4-46c0-b425-9383d16a6b24.png)

![image](https://user-images.githubusercontent.com/36693835/158113694-f2c7794e-fdca-4c87-ade9-775664eabd43.png)

`    for x in range(3):
        input()
        lis = input().split()
        lis.reverse()
        print(' '.join(lis))
        del_item = input()
        while del_item in lis:
            lis.remove(del_item)
        if len(lis) == 0:
            print()
        else:
            print(' '.join(lis))`

`#include<stdio.h>
#include<string.h>
int main(){
    char* a[1001];
    char x[1001][1001],key[1001];
    int i=0;
    for(int t=0;t<3;t++){
        int n;
        scanf("%d",&n);         //输入该组数据个数
        for(i=0;i<n;i++){   //输入该组数据
            scanf("%s",&x[i]);
            a[i]=x[i];
        }
        scanf("%s",&key);       //输入要删除数字
        for(i=n-1;i>=0;i--){
            printf("%s ",a[i]); //将该组数据倒着输出
        }
        printf("\n");
        for(i=n-1;i>=0;i--){    //删除选中数字后倒着输出
            if(strcmp(a[i],key)!=0){
                printf("%s ",a[i]);
            }
        }
        printf("\n");
    }
}`

**Comment by chanbaihai** [comment]
> 题目的输出格式和输入格式非常重要，规定的这道题目中应该以什么样的方式进行输入输出。

![image](https://user-images.githubusercontent.com/36693835/158296438-a3a5fc0b-5c39-4eef-8371-cd2d2f5ee951.png)
希望NOJ能像leetcode有这种提示，不然很多时候用例不同都不知道错在哪里，只是个建议哈

**Comment by ZsgsDesign** [comment]
是可以的，在CodeForces中也有类似的预测试。不过需要评测机和主服务进行很多的改动，目前评测机已经支持返回对拍数据了，主服务端的改动比较复杂，这一功能的实现主要记录在 #313。
