### ISSUE TITLE
cannot send verify email ...

### ISSUE THREAD

**Issue by X3ZvaWQ** [ZsgsDesign/NOJ#93]
**Describe the bug**
SMTP login should use special authorization code instead of QQ password when sending verification mail... 
see:
http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256

**To Reproduce**
1. Go to 'setting'
2. Click on 'SEND EMAIL'
3. See error

**Expected behavior**
Failed to authenticate on SMTP server with username "nuptacm@qq.com" using 1 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 Error: ��ʹ����Ȩ���¼�������뿴: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256 "..

**Comment by ZsgsDesign** [comment]
This is a known issue related to QQ Mail's policy, we are not intended to fix that right now because we are going to using third-party mailing services in the future.
